// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "ctre/Phoenix.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<WPI_TalonSRX> RobotMap::driveBaseLeftMotor1;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveBaseRightMotor1;
std::shared_ptr<frc::DifferentialDrive> RobotMap::driveBaseDiffDrive;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveBaseLeftMotor2;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveBaseRightMotor2;
std::shared_ptr<WPI_TalonSRX> RobotMap::elevatorLiftMotor;
std::shared_ptr<frc::SpeedController> RobotMap::intakeLeftIntakeMotor;
std::shared_ptr<frc::SpeedController> RobotMap::intakeRightIntakeMotor;
std::shared_ptr<frc::Compressor> RobotMap::pneumaticsCompressor;
std::shared_ptr<frc::Solenoid> RobotMap::pneumaticsIntakeSolenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    frc::LiveWindow *lw = frc::LiveWindow::GetInstance();

    driveBaseLeftMotor1.reset(new WPI_TalonSRX(1));
    
    
    driveBaseRightMotor1.reset(new WPI_TalonSRX(3));
    
    
    driveBaseDiffDrive.reset(new frc::DifferentialDrive(*driveBaseLeftMotor1, *driveBaseRightMotor1));
    lw->AddActuator("DriveBase", "DiffDrive", driveBaseDiffDrive);
    driveBaseDiffDrive->SetSafetyEnabled(true);
        driveBaseDiffDrive->SetExpiration(0.1);
        driveBaseDiffDrive->SetMaxOutput(1.0);

    driveBaseLeftMotor2.reset(new WPI_TalonSRX(2));
    
    
    driveBaseRightMotor2.reset(new WPI_TalonSRX(4));
    
    
    elevatorLiftMotor.reset(new WPI_TalonSRX(5));
    
    
    intakeLeftIntakeMotor.reset(new frc::Talon(0));
    lw->AddActuator("Intake", "LeftIntakeMotor", std::static_pointer_cast<frc::Talon>(intakeLeftIntakeMotor));
    
    intakeRightIntakeMotor.reset(new frc::Talon(1));
    lw->AddActuator("Intake", "RightIntakeMotor", std::static_pointer_cast<frc::Talon>(intakeRightIntakeMotor));
    
    pneumaticsCompressor.reset(new frc::Compressor(0));
    lw->AddActuator("Pneumatics", "Compressor", pneumaticsCompressor);
    
    pneumaticsIntakeSolenoid.reset(new frc::Solenoid(0, 1));
    lw->AddActuator("Pneumatics", "IntakeSolenoid", pneumaticsIntakeSolenoid);
    


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
