// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "Robot.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "ctre/Phoenix.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<WPI_TalonSRX> RobotMap::driveBaseLeftMotor1;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveBaseRightMotor1;
std::shared_ptr<frc::DifferentialDrive> RobotMap::driveBaseDiffDrive;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveBaseLeftMotor2;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveBaseRightMotor2;
std::shared_ptr<frc::Solenoid> RobotMap::clampFldClamp;
std::shared_ptr<frc::Compressor> RobotMap::clampFldCompressor;
std::shared_ptr<frc::SpeedController> RobotMap::elevatorElevatorMotor;
std::shared_ptr<frc::SpeedController> RobotMap::intakeIntakeMotor1;
std::shared_ptr<frc::SpeedController> RobotMap::intakeIntakeMotor2;
std::shared_ptr<frc::Solenoid> RobotMap::clampClamper;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    frc::LiveWindow *lw = frc::LiveWindow::GetInstance();

    driveBaseLeftMotor1.reset(new WPI_TalonSRX(1));
    
    
    driveBaseRightMotor1.reset(new WPI_TalonSRX(3));
    
    
    driveBaseDiffDrive.reset(new frc::DifferentialDrive(*driveBaseLeftMotor1, *driveBaseRightMotor1));
    lw->AddActuator("DriveBase", "DiffDrive", driveBaseDiffDrive);
    driveBaseDiffDrive->SetSafetyEnabled(true);
        driveBaseDiffDrive->SetExpiration(0.1);
        driveBaseDiffDrive->SetMaxOutput(1.0);

    driveBaseLeftMotor2.reset(new WPI_TalonSRX(2));
    
    
    driveBaseRightMotor2.reset(new WPI_TalonSRX(4));
    
    
    clampFldClamp.reset(new frc::Solenoid(0, 0));
    lw->AddActuator("ClampFld", "Clamp", clampFldClamp);
    
    clampFldCompressor.reset(new frc::Compressor(0));
    lw->AddActuator("ClampFld", "Compressor", clampFldCompressor);
    
    elevatorElevatorMotor.reset(new frc::Talon(0));
    lw->AddActuator("Elevator", "ElevatorMotor", std::static_pointer_cast<frc::Talon>(elevatorElevatorMotor));
    
    intakeIntakeMotor1.reset(new frc::Talon(1));
    lw->AddActuator("Intake", "IntakeMotor1", std::static_pointer_cast<frc::Talon>(intakeIntakeMotor1));
    
    intakeIntakeMotor2.reset(new frc::Talon(2));
    lw->AddActuator("Intake", "IntakeMotor2", std::static_pointer_cast<frc::Talon>(intakeIntakeMotor2));
    
    clampClamper.reset(new frc::Solenoid(0, 1));
    lw->AddActuator("Clamp", "Clamper", clampClamper);
    


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
